### ISSUE TITLE
luna runtime executable

### ISSUE THREAD

**Issue by lolrobbe2** [lolrobbe2/luna#25]
# tasks
- [x] load runtime.ini file
- [x] interpret runtime.ini file
- [ ] load asset packages (asset manager)
- [x] load start scene
- [x] initialze appropriate engine components
- [x] add IMGUI disable macro
- [ ] load appropriate scene C# lib 
## runtime.ini 
- startup scene location
-
